// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// exp_moving_avg
NumericVector exp_moving_avg(NumericVector x, double decay, int min_size);
RcppExport SEXP rqfin_exp_moving_avg(SEXP xSEXP, SEXP decaySEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_moving_avg(x, decay, min_size));
    return rcpp_result_gen;
END_RCPP
}
// ffill
NumericVector ffill(NumericVector x, int w);
RcppExport SEXP rqfin_ffill(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(ffill(x, w));
    return rcpp_result_gen;
END_RCPP
}
// first_true
int first_true(LogicalVector x);
RcppExport SEXP rqfin_first_true(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(first_true(x));
    return rcpp_result_gen;
END_RCPP
}
// last_true
int last_true(LogicalVector x);
RcppExport SEXP rqfin_last_true(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(last_true(x));
    return rcpp_result_gen;
END_RCPP
}
// running_min
NumericVector running_min(NumericVector x, int w, size_t min_size);
RcppExport SEXP rqfin_running_min(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_min(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_max
NumericVector running_max(NumericVector x, int w, size_t min_size);
RcppExport SEXP rqfin_running_max(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_max(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_mean
NumericVector running_mean(NumericVector x, int w, int min_size);
RcppExport SEXP rqfin_running_mean(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_mean(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_sd
NumericVector running_sd(NumericVector x, int w, int min_size);
RcppExport SEXP rqfin_running_sd(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_sd(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_sd0
NumericVector running_sd0(NumericVector x, int w, int min_size);
RcppExport SEXP rqfin_running_sd0(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_sd0(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_sum
NumericVector running_sum(NumericVector x, int w, int min_size);
RcppExport SEXP rqfin_running_sum(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_sum(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
